[".local/share/tmux/oh-my-tmux"]
    type = "git-repo"
    url = "https://github.com/gpakosz/.tmux.git"
    refreshPeriod = "168h"
    [".local/share/tmux/oh-my-tmux".pull]
        args = ["--ff-only"]

[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    refreshPeriod = "168h"
    [".oh-my-zsh".pull]
        args = ["--ff-only"]
